### ISSUE TITLE
Really long loading times or not loading at all.

### ISSUE THREAD

**Issue by Danielosama** [Madmanmayson/KanColleViewer#1]
Yesterday it was working just fine, but today it just doesn't load.
I've cleared cache multiple times, set the cookies again, checked Adobe Flash, and still it just won't load.
This morning it would get stuck on the "white screen", later on, on the black screen with the ship, and now the loading bar won't budge.
However, when I play with KC3Kai it loads without any problem at all, so at this point I believe something is up with IE, but I can not figure out what.
Any ideas?

**Comment by Madmanmayson** [comment]
If it doesn't make it to the start button it definitely sounds like either IE or the Kancolle Servers are just running slow. I'd first try it again more more time and if it gets stuck try clicking reload instead of closing and reopening the program and see if that works.

**Comment by Danielosama** [comment]
I gave up and spent the rest of the way working and so on.
Tried again now, and works just fine.
Guess IE was acting up for some reason.
Thanks for keeping KCV up to date btw, it's the only way I can play KC since I can't stand KC3's UI :>
