### ISSUE TITLE
HTML5 Update

### ISSUE THREAD

**Issue by Danielosama** [Madmanmayson/KanColleViewer#2]
Does this still work with the new update?
I only get a black screen unfortunately.

**Comment by Danielosama** [comment]
I see, thanks for the answer.
Will have to use KC3Kai for now then.

**Comment by Madmanmayson** [comment]
Thankfully Grabacr07 created an update for the main japanese branch that has now been upstreamed and version 4.5 created. No guarantees every feature works but if there are any issues just create a new issue and I'll see what I can do.

Also I'm now going to be going back to adding features so any requests you can also raise an issue for and I'll see what I can do, no promises.
