### ISSUE TITLE
Cache Question

### ISSUE THREAD

**Issue by Danielosama** [Madmanmayson/KanColleViewer#5]
Hey man, sorry to open a new issue to ask a question, but I don't know any other way to contact you :x 
Anyways, I was wondering what cache does KCV use right now, IE/Edge or Chrome?
Thanks for the answer.

**Comment by Madmanmayson** [comment]
Sorry been busy for a while (retail jobs always suck around the holidays) so I didn't respond right away. I know that it uses chromium as a mini browser now though I don't know if it shares a cache with either IE, Chrome or has its own personal one. I use Firefox as my main browser so I would have to mess around with it next weekend and see which one it does use. 

PS: you can also add and message me on discord as I'm much more active there @Madmanmayson#2337

**Comment by Danielosama** [comment]
Got it, thanks for the answer.

I just sent you a request through Discord, I'll be sure to message you there for any further questions.
