### ISSUE TITLE
Expedition Claim Bug?

### ISSUE THREAD

**Issue by drhomieg** [Madmanmayson/KanColleViewer#8]
Hey, I've been getting a bug where I get stuck for an abnormally long time when my expeditions come back.  I click on them, but sometimes I have to wait ages for them to actually show the Success/Great Success pages.  Sometimes, after like 5+ mins if the page still hasn't loaded, I refresh the viewer. 

I recently switched over from Yuubari's to your viewer since the new update if that helps at all.

**Comment by Madmanmayson** [comment]
Hmmm well right now the only major difference between my 11.1 version and Yuubari's 11.0 version is the update to the BattleInfoPlugin to support the changes to the combat API and to hopefully fix an issue with the Calculator Plugin slowing some things down so you could try removing the Calculator.dll from the plugin's folder and see if that fixes it. I've had it be delayed by a few seconds before especially during an event but thats usually on the Kancolle Server side but having to wait that long sounds more like it timing out on Kancolle's end.
